name: preview-pr

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  authorize:
    environment:
      ${{ github.event_name == 'pull_request_target' &&
      github.event.pull_request.head.repo.full_name != github.repository &&
      'external' || 'internal' }}
    runs-on: ubuntu-latest
    steps:
      - run: "true"

  # The PR code is built without access to any secret
  build:
    needs: authorize
    uses: ./.github/workflows/build.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
      - name: Extract site
        run: mkdir dist && tar -xf artifact.tar -C dist
      - name: Publish to Cloudflare Pages
        id: preview-pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT }}
          command: pages deploy dist --project-name=hack-gpon-preview --branch=preview
      - uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Preview of the website obtained from the PR: ${{ steps.preview-pages.outputs.deployment-url }}
